name: Auto approve and merge trusted PRs

on:
  pull_request_target:

jobs:
  approve:
    runs-on: ubuntu-latest
    name: Approve
    if: github.actor == 'jimscard' || github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    name: Auto-merge
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    needs: approve
    if: github.actor == 'jimscard' || github.actor == 'dependabot[bot]'
    steps:
      - uses: reitermarkus/automerge@v2.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          do-not-merge-labels: do-not-merge, wip
          required-labels: ready-to-merge
          pull-request: ${{ github.event.pull_request.number }}
