name: Auto approve and merge trusted PRs
on:
  pull_request:
    types: [opened, synchronize]  # Trigger the workflow on pull request open and synchronize events
jobs:
  approve:
    runs-on: ubuntu-latest  # Specify the environment to run the job
    if: github.actor == 'jimscard' || github.actor == 'dependabot[bot]'  # Condition to run this job only for specific users
    permissions:
      pull-requests: write  # Grant write permissions to pull requests
    steps:
      - uses: hmarr/auto-approve-action@v4  # Use the auto-approve action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Provide the GitHub token for authentication
  auto-merge:
    name: Auto-merge  # Name of the job
    runs-on: ubuntu-latest  # Specify the environment to run the job
    permissions:
      contents: write  # Grant write permissions to repository contents
      pull-requests: write  # Grant write permissions to pull requests
    needs: approve  # This job depends on the successful completion of the 'approve' job
    if: github.actor == 'jimscard' || github.actor == 'dependabot[bot]'  # Condition to run this job only for specific users
    steps:
      - uses: reitermarkus/automerge@v2.8.0  # Use the automerge action
        with:
          token: ${{ secrets.BUMP_CASK_TOKEN }}  # Provide the GitHub token for authentication
          merge-method: squash  # Use squash method for merging
          do-not-merge-labels: do-not-merge, wip  # Labels that prevent merging
          required-labels: ready-to-merge  # Labels required for merging
          pull-request: ${{ github.event.pull_request.number }}  # Specify the pull request number
