name: Auto approve trusted
on:
  pull_request_target:

permissions:
  pull-requests: write

jobs:
  approve:
    runs-on: ubuntu-latest
    name: approve
    steps:
      - uses: hmarr/auto-approve-action@v4
        if: github.actor == 'jimscard'
      - uses: hmarr/auto-approve-action@v4
        if: github.actor == 'dependabot[bot]'
  auto-merge:
    name: auto-merge
    runs-on: ubuntu-latest
    needs: approve
    steps:
      # You may pin to the exact commit or the version.
      # uses: reitermarkus/automerge@634d0a4b51134c163eee182ac9aa79133eb33e8d
      - uses: reitermarkus/automerge@v2.8.0
        with:
          token: ${{ secrets.BUMPER_TOKEN }} # Ensure the token is set correctly
          merge-method: merge # Set a default merge method
          review-author-associations: OWNER,MEMBER,COLLABORATOR # Default value
          dry-run: false # Ensure this is set correctly
