name: Auto approve trusted
on:
  pull_request_target:

jobs:
  approve:
    runs-on: ubuntu-latest

    name: approve
    if: github.actor == 'jimscard'
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.BUMPER_TOKEN }} # Ensure the token is set correctly

    # if: github.actor == 'dependabot'
    # steps:
    #   - uses: hmarr/auto-approve-action@v4

  auto-merge:
    name: auto-merge
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: approve
    steps:
      - uses: reitermarkus/automerge@v2.8.0
        with:
          token: ${{ secrets.BUMPER_TOKEN }} # Ensure the token is set correctly
          merge-method: merge # Set a default merge method
          review-author-associations: OWNER,MEMBER,COLLABORATOR # Default value
          dry-run: false # Ensure this is set correctly
